collections:
  journal:
    output: true

url: "https://pupsabin.dog"
timezone: America/New_York
baseurl: ""
attachments_dir: "assets/imgs/attachments"

progress_tracker:
  monthly_goal: 20

plugins:
  - jekyll-seo-tag
  - jekyll-minifier

defaults:
  - scope:
      path: ""
      type: "journal"
    values:
      image: https://assets.pupsabin.dog/IMG_1064.jpeg
      description: "A view into the life of gearhead werehusky sergal thing, Pup Sabin, one journal entry at a time."

jekyll-minifier:
  exclude: ["feed.xml", "assets/search.json"]
  compress_javascript: true
  uglifier_args:
    harmony: true