collections:
  journal:
    output: true

url: "https://pupsabin.dog"
timezone: America/New_York
baseurl: ""
attachments_dir: "assets/imgs/attachments"

progress_tracker:
  monthly_goal: 20

plugins:
  - jekyll-seo-tag
  - jekyll-minifier

defaults:
  - scope:
      path: ""
      type: "journal"
    values:
      image: assets/imgs/Journal_Image.jpg
      description: "A view into the life of gearhead werehusky sergal thing, Pup Sabin, one journal entry at a time."

jekyll-minifier:
  exclude: ["feed.xml", "assets/search.json"]
  compress_javascript: true
  uglifier_args:
    harmony: true

navbar:
  - name: "index"
    label: "Home"
    url: "/index.html"
  - name: "gallery"
    label: "Gallery"
    url: "/gallery.html"
  - name: "journal"
    label: "Journal"
    url: "/journal/welcome.html"
  - name: "ama"
    label: "Ask Me"
    url: "/ama.html"

moods:
  success:
    - affectionate
    - confident
    - productive
    - proud
    - upbeat
  warning:
    - annoyed
    - restless
    - tired
    - unfocused
  primary:
    - calm
    - reflective
    - bored
  danger:
    - angry