collections:
  journal:
    output: true
    permalink: /Journal/:path.html

url: "https://pupsabin.dog"
timezone: America/New_York
baseurl: ""
attachments_dir: "assets/imgs/attachments"

feed:
  path: feed.xml
  collections:
    - journal  

progress_tracker:
  monthly_goal: 20

plugins:
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "journal"
    values:
      image: assets/imgs/Journal_Image.jpg
      description: "A view into the life of gearhead werehusky sergal thing, Pup Sabin, one journal entry at a time."
