collections:
  journal:
    output: true
    permalink: /Journal/:path.html

url: "https://pupsabin.dog"
baseurl: ""

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "journal"
    values:
      image: imgs/Main_Image.jpg
      description: "A view into the life of Pup Sabin, one journal entry at a time."
