collections:
  journal:
    output: true
    permalink: /Journal/:path.html

url: "https://pupsabin.dog"
baseurl: ""

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "journal"
    values:
      image: assets/imgs/Journal_Image.png
      description: "A view into the life of gearhead werehusky sergal thing, Pup Sabin, one journal entry at a time."
