name: Build & Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  RUBY_VERSION: '3.1.2'
  CF_PAGES_PROJECT: 'sabindarkstone-github-io'
  BUILD_DIR: /_site
  JEKYLL_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: site-dist
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby & Bundler (cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: site/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('site/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Node (for SCSS build)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-json.json

      - name: Install npm dependencies
        run: npm ci

      - Build CSS:
        run: npm build:css
      
      - name: Install gems
        working-directory: site
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll
        working-directory: site
        run: |
          bundle exec jekyll build --trace

      - name: Upload built site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: ${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name ${{ env.CF_PAGES_PROJECT }} --branch=main