name: Build Quartz Site
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Quartz
        uses: konstfish/quartz-build-action@v6
        with:
          source: content
          page_title: "Pup Sabin - Journal"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages           # ← required
      url: ${{ steps.deployment.outputs.page_url }}  # ← optional, shows a "View deployment" link
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
