name: Deploy Jekyll Journal
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.x

      - name: Install Jekyll & Gems
        run: |
          gem install bundler jekyll github-pages

      - name: Build site
        run: jekyll build --source . --destination sites/Journal

      - uses: actions/upload-pages-artifact@v1
        with:
          path: sites/Journal

      - uses: actions/deploy-pages@v1
        with:
          artifact_path: sites/Journal
