name: Build & Deploy Journal

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4                                                      # checkout code :contentReference[oaicite:8]{index=8}
      - name: Setup Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true                                                          # caches your bundle :contentReference[oaicite:9]{index=9}
      - name: Install Gems
        working-directory: ./site/
        run: bundle install                                                            # installs via your Gemfile :contentReference[oaicite:10]{index=10}
      - name: Build Jekyll site
        working-directory: ./site/
        run: bundle exec jekyll build \
          --source notes \
          --destination site/Journal
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/Journal
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
